# Generated by Django 5.2.5 on 2025-09-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_liked_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
