# Generated by Django 5.2.5 on 2025-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='profile_pic_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
