# Generated by Django 5.2.5 on 2025-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userauth_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='apple_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
