# Generated by Django 5.2.5 on 2025-08-21 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False)),
                ('times_visited', models.PositiveIntegerField(default=0)),
                ('lived_here', models.BooleanField(default=False)),
                ('bucket_list', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('add_photos', models.ImageField(blank=True, null=True, upload_to='travel_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to='locations.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'country')},
            },
        ),
    ]
