# Generated by Django 5.2.5 on 2025-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_travelrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='photos_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
