# Generated by Django 5.2.5 on 2025-09-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_travelrecord_photos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrecord',
            name='add_photos',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='photos_title',
        ),
        migrations.CreateModel(
            name='TravelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_photos/')),
                ('title', models.CharField(max_length=255)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('travel_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='locations.travelrecord')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
