# Generated by Django 5.2.5 on 2025-09-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_travelrecord_add_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelphoto',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelphoto',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='travelphoto',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
