# Generated by Django 5.2.5 on 2025-09-09 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_system', '0002_block_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='requester',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('requester', 'receiver')},
        ),
    ]
